#!/bin/bash
# run the django fcgi server

echo "run this as ecotrust. you are:"
whoami
ps aux | grep "django_app/manage.py runfcgi" | grep -v grep | awk '{system("kill " $2)}'
source /usr/local/apps/terratruth/ENV/bin/activate
python /usr/local/apps/terratruth/django_app/manage.py runfcgi method=threaded host=127.0.0.1 port=3033
echo successfully ran TERRATRUTH restart script

