#!/bin/bash
# run the django fcgi server

sudo ps aux | grep "django_app/manage.py runfcgi" | grep -v grep | awk '{system("sudo kill " $2)}'
sudo su www-data
source /usr/local/apps/terratruth/ENV/bin/activate
python /usr/local/apps/terratruth/django_app/manage.py runfcgi method=threaded host=127.0.0.1 port=3033
echo successfully restarted AMNDSS

